name: "📌 Create"
description: "기능이나 파일들을 추가 및 생성하는 작업"
labels: 생성
assignees: assign yourself
body:
  - type: textarea
    attributes:
      label: 설명
      description: |
        추가할 기능을 작성해주세요.
      placeholder: |
        이기능을 추가할래요.
  - type: textarea
    attributes:
      label: 추가사항
      description: |
        추가사항이 있어요!