name: "🍬 Refactoring"
description: "코드를 리펙토링하는 작업"
labels: 리펙토링
assignees: assign yourself
body:
  - type: textarea
    attributes:
      label: 설명
      description: |
        리펙토링할 부분을 작성해주세요.
      placeholder: |
        이코드가 더러워요.
  - type: textarea
    attributes:
      label: 추가사항
      description: |
        추가사항이 있어요!